ws:
  addr: ":8081"

rabbitmq:
  host: ""
  port: "5672"
  user: "user"
  password: "passwd"
  exchange_name: "ngb_direct"
  ws_routing_key:
    - "mentioned"
    - "comment"
    - "message"
    - "new_post"
  email_routing_key:
    - "none"

jwt:
  secret: ""

postgresql:
  user: "user"
  password: "passwd"
  dbname: "ngb_beta"
  host: ""
  port: "5432"

mail:
  host : "smtp.example.com"
  addr : "smtp.example.com:587"
  username : "xxxx@example.com"
  password : ""
  goroutine: 10
  template: ""

redis:
  host: ""
  port: "6379"

log:
  path: "log"
  file: "log"
